CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP
);

INSERT INTO users (username, email, password, role, enabled, created_at)
SELECT 'admin', 'admin@example.com', '$2a$12$vHXjKa9a/X/QT9PGWgpj6OPQ2vqiH7q7q7q7q7q7q7q7q7q7q7q7q', 'ADMIN', true, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE username = 'admin' OR email = 'admin@example.com'
);

INSERT INTO users (username, email, password, role, enabled, created_at)
SELECT 'user1', 'user1@example.com', '$2a$12$vHXjKa9a/X/QT9PGWgpj6OPQ2vqiH7q7q7q7q7q7q7q7q7q7q7q7q', 'USER', true, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE username = 'user1' OR email = 'user1@example.com'
);
